# Generated by Django 2.2.9 on 2020-01-02 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.CharField(default='placeholder', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 21, 27, 25, 785330), verbose_name='date published'),
        ),
    ]
