# Generated by Django 2.2.9 on 2020-02-02 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200201_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='image_alt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 19, 24, 17, 168776), verbose_name='date published'),
        ),
    ]
